-- 1. Create table if not exists (base structure)
CREATE TABLE IF NOT EXISTS public.platform_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    site_name TEXT DEFAULT 'Beyan Dil Akademi',
    site_description TEXT,
    contact_email TEXT,
    support_email TEXT,
    max_enrollments_per_user INTEGER DEFAULT 5,
    allow_new_registrations BOOLEAN DEFAULT true,
    maintenance_mode BOOLEAN DEFAULT false,
    announcement_bar_enabled BOOLEAN DEFAULT false,
    announcement_text TEXT,
    announcement_color TEXT DEFAULT '#000000',
    whatsapp_enabled BOOLEAN DEFAULT false,
    whatsapp_number TEXT,
    whatsapp_message TEXT,
    
    -- Expanded columns (ensure they exist)
    logo_url TEXT,
    favicon_url TEXT,
    hero_title TEXT,
    hero_description TEXT,
    hero_image_url TEXT,
    footer_description TEXT,
    contact_phone TEXT,
    contact_address TEXT,
    social_links JSONB DEFAULT '[]'::jsonb,
    features_section JSONB DEFAULT '[]'::jsonb,
    testimonials_section JSONB DEFAULT '[]'::jsonb,
    founder_section JSONB DEFAULT '{}'::jsonb
);

-- 2. Enable RLS
ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies

-- Allow everyone to read settings
DROP POLICY IF EXISTS "Public can view platform_settings" ON public.platform_settings;
CREATE POLICY "Public can view platform_settings"
ON public.platform_settings FOR SELECT
USING (true);

-- Allow admins to update settings
DROP POLICY IF EXISTS "Admins can update platform_settings" ON public.platform_settings;
CREATE POLICY "Admins can update platform_settings"
ON public.platform_settings FOR ALL
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role = 'admin'
    )
);

-- 4. Insert default row if not exists
INSERT INTO public.platform_settings (id, site_name)
VALUES (1, 'Beyan Dil Akademi')
ON CONFLICT (id) DO NOTHING;
