
export const dailyTips = [
    { title: "İstikrar", content: "Küçük adımlar, büyük mesafeler kat ettirir. Her gün 15 dakika, haftada bir gün 5 saatten daha değerlidir." },
    { title: "Tekrar", content: "Öğrendiklerinizi pekiştirmenin en iyi yolu, onları başkalarına anlatmaktır." },
    { title: "Hata Yapmak", content: "Hata yapmaktan korkmayın. Her hata, öğrenme sürecinin doğal ve gerekli bir parçasıdır." },
    { title: "Dil Öğrenimi", content: "Bir lisan, bir insan demektir. Yeni bir dil, yeni bir dünyaya açılan kapıdır." },
    { title: "Kelime Hazinesi", content: "Her gün yeni bir kelime öğrenmek, yılda 365 yeni kelime demektir. Kelime kartları kullanmayı deneyin." },
    { title: "Dinleme", content: "Pasif dinleme de öğrenmenin bir parçasıdır. Arka planda o dilde radyo veya podcast dinleyin." },
    { title: "Okuma", content: "Seviyenize uygun kitaplar okumak, gramer yapılarını doğal yolla öğrenmenizi sağlar." },
    { title: "Konuşma", content: "Kendi kendinize konuşmak delilik değil, pratiktir! Aynanın karşısında öğrendiklerinizi tekrar edin." },
    { title: "Motivasyon", content: "Neden başladığınızı asla unutmayın. Hedefinizi bir kağıda yazıp görebileceğiniz bir yere asın." },
    { title: "Soru Sormak", content: "Merak ilmin hocasıdır. Anlamadığınız her şeyi sorun, soru sormaktan çekinmeyin." },
    { title: "Sabır", content: "Dil öğrenmek bir maratondur, sprint değil. Kendinize zaman tanıyın." },
    { title: "Not Alma", content: "Yazarak çalışmak, bilgilerin hafızada daha kalıcı olmasını sağlar. Renkli kalemler kullanın." },
    { title: "Kültür", content: "Bir dili öğrenmek, o kültürü de öğrenmektir. O dile ait filmler izleyin, müzikler dinleyin." },
    { title: "Planlama", content: "Haftalık çalışma planı yapın. Hangi gün ne çalışacağınızı bilmek sizi disipline sokar." },
    { title: "Uyku", content: "Öğrenilen bilgilerin pekişmesi için kaliteli uyku şarttır. Uykunuzu ihmal etmeyin." },
    { title: "Teknoloji", content: "Telefonunuzun dilini öğrendiğiniz dile çevirin. Bu, maruz kalma sürenizi artırır." },
    { title: "Arkadaş", content: "Dil değişim arkadaşı bulun. Karşılıklı pratik yapmak gelişiminizi hızlandırır." },
    { title: "Gramer", content: "Gramer kurallarına takılıp kalmayın. İletişim kurmaya odaklanın, kurallar zamanla oturur." },
    { title: "Cesaret", content: "Mükemmel olmayı beklemeyin. Yarım yamalak da olsa konuşmaya başlayın." },
    { title: "Kaydetme", content: "Kendi sesinizi kaydedin ve dinleyin. Telaffuz hatalarınızı fark etmenin en iyi yoludur." },
    { title: "Çeviri", content: "Her şeyi kelimesi kelimesine çevirmeye çalışmayın. Bağlamı anlamaya odaklanın." },
    { title: "Altyazı", content: "Dizi izlerken önce Türkçe altyazılı, sonra hedef dilde altyazılı, en son altyazısız izleyin." },
    { title: "Günlük", content: "Öğrendiğiniz dilde günlük tutun. Basit cümlelerle gününüzü anlatın." },
    { title: "Düşünme", content: "İç sesinizi öğrendiğiniz dile çevirmeye çalışın. 'Bunu nasıl derdim?' diye düşünün." },
    { title: "Oyun", content: "Kelime oyunları ve bulmacalar, eğlenerek öğrenmenin harika bir yoludur." },
    { title: "Seyahat", content: "İmkânınız varsa o dilin konuşulduğu ülkeye gidin veya sanal turlar yapın." },
    { title: "Taklit", content: "Ana dili o olan kişileri taklit edin. Vurgu ve tonlama anlamı tamamen değiştirebilir." },
    { title: "Müzik", content: "Şarkı sözlerini çevirin ve eşlik edin. Telaffuzunuzu geliştirmek için harika bir yöntemdir." },
    { title: "Görselleştirme", content: "Kelimeleri resimlerle eşleştirin. Beynimiz görselleri metinlerden daha iyi hatırlar." },
    { title: "Süreklilik", content: "Günde 1 saat çalışıp 3 gün ara vermek yerine, her gün 20 dakika çalışın." },
    { title: "Ödül", content: "Küçük hedefler koyun ve bunlara ulaştığınızda kendinizi ödüllendirin." },
    { title: "Çocuk Kitapları", content: "Başlangıç seviyesindeyseniz çocuk kitapları okuyun. Dili basit ve anlaşılırdır." },
    { title: "Haberler", content: "Dünya gündemini öğrendiğiniz dilden takip etmeye çalışın." },
    { title: "Sosyal Medya", content: "O dili konuşan hesapları takip edin. Günlük konuşma dilini öğrenmenize yardımcı olur." },
    { title: "Deyimler", content: "Deyimler dilin tuzudur biberidir. Her hafta bir deyim öğrenin." },
    { title: "Zaman Yönetimi", content: "Ölü zamanları değerlendirin. Otobüste, kuyrukta beklerken kelime çalışın." },
    { title: "Odaklanma", content: "Çalışırken telefon bildirimlerini kapatın. Tam odaklanma verimi artırır." },
    { title: "Geri Bildirim", content: "Hatalarınızın düzeltilmesinden rahatsız olmayın, teşekkür edin." },
    { title: "Sesli Okuma", content: "Metinleri sesli okuyun. Hem okuma hem konuşma beceriniz gelişir." },
    { title: "Rutin", content: "Dil öğrenmeyi diş fırçalamak gibi günlük rutininizin bir parçası haline getirin." },
    { title: "Post-it", content: "Evinizdeki eşyaların üzerine o dildeki isimlerini yazan kağıtlar yapıştırın." },
    { title: "Sözlük", content: "Resimli sözlükler kullanın. Kelime ile nesne arasında doğrudan bağ kurarsınız." },
    { title: "Podcast", content: "Özellikle dil öğrenenler için hazırlanmış yavaş konuşulan podcastleri dinleyin." },
    { title: "Şiir", content: "Şiir okumak dilin ritmini ve duygusunu hissetmenizi sağlar." },
    { title: "Tarifler", content: "Yemek tariflerini o dilde okuyup uygulamaya çalışın." },
    { title: "Navigasyon", content: "Harita uygulamanızın dilini değiştirin. Yön tariflerini öğrenirsiniz." },
    { title: "Liste", content: "Alışveriş listenizi veya yapılacaklar listenizi o dilde hazırlayın." },
    { title: "Tekerleme", content: "Tekerlemeler söylemek dil kaslarınızı o dile alıştırır ve telaffuzu geliştirir." },
    { title: "Vazgeçmemek", content: "En önemlisi asla vazgeçmeyin. Zorlandığınız an, geliştiğiniz andır." },
    { title: "Keyif", content: "Sürecin tadını çıkarın. Yeni bir dil öğrenmek, yeni bir hayat yaşamaktır." }
];

// Add this to your existing mock data exports if needed, or keep separate
